language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8.9'
before_script:
  - npm prune
script:
  - npm run test
